### PR TITLE
play music when TieDB starts

### PR DESCRIPTION
**Pull request by miyuri-fox**

### CODE REVIEW

**Comment by miyuri-fox** [comment]
@sre-bot /tests

**Comment by miyuri-fox** [comment]
@sre-bot /tests

**Comment by miyuri-fox** [comment]
@sre-bot /run-integration-test

**Comment by miyuri-fox** [comment]
@sre-bot /run-integration-test

**Comment by miyuri-fox** [comment]
@sre-bot /run-integration-test

**Comment by miyuri-fox** [comment]
@sre-bot /run-all-tests

**Comment by miyuri-fox** [comment]
@sre-bot /run-all-tests

**Comment by miyuri-fox** [comment]
@sre-bot /run-all-tests

**Comment by miyuri-fox** [comment]
@sre-bot /run-all-tests

**Comment by miyuri-fox** [comment]
@sre-bot /merge

**Comment by miyuri-fox** [comment]
@sre-bot /run-all-tests

**Review by you06 — APPROVED** [review]
LGTM

**Pull request merged**
